source 'https://rubygems.org'

gem 'wordtree', :github => 'wordtreefoundation/wordtree-ruby'
gem 'rethinkdb'
gem 'rethinkdb_job', :github => 'wordtreefoundation/rethinkdb_job'
gem 'sinatra'
gem 'unicorn'
gem 'stalker'

group :development, :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'guard'
  gem 'guard-rspec'
  gem 'debugger'
end