#!/usr/bin/env ruby

require 'wordtree'
require 'json'

rdb = {
  :host => ENV['RDB_HOST'],
  :port => ENV['RDB_PORT'],
  :db   => ENV['RDB_DB'],
}

puts "Connecting to RethinkDB... #{rdb.to_json}"
db = WordTree::DB::Librarian.new(rdb)

puts "Initializing Disk Library ('#{ENV['LIBRARY']}')"
disk = WordTree::Disk::Librarian.new(ENV['LIBRARY'])

puts "Environment: \n#{JSON.pretty_generate(ENV.to_hash)}"

disk.each do |book|
  puts "#{book.id} (#{book.year})..."
  begin
    book_in_db = db.find(book.id)
    if book_in_db
      puts " ** book already in DB"
    end
    if ENV['overwrite']
      puts " ** saving (overwrite set)"
      db.save(book)
    elsif book_in_db.nil?
      puts " ** saving (not in DB yet)"
      db.save(book)
    else
      puts " ** skipping"
    end
  rescue StandardError => e
    puts " ** unable to save: #{e}"
  end
end
