#!/usr/bin/env ruby

require 'wordtree'
require 'json'

rdb = {
  :host => ENV['RDB_HOST'],
  :port => ENV['RDB_PORT'],
  :db   => ENV['RDB_DB'] || 'research',
}

puts "Connecting to RethinkDB... #{rdb.to_json}"
$db = WordTree::DB::Librarian.new(rdb)

puts "Initializing Disk Library ('#{ENV['LIBRARY']}')"
$disk = WordTree::Disk::Librarian.new(ENV['LIBRARY'])

puts "Environment: \n#{JSON.pretty_generate(ENV.to_hash)}"

def save_book(book_id)
  book = $disk.find(book_id)
  $db.save(book)
end

$disk.library.each do |path, book_id|
  puts path
  begin
    book_in_db = $db.find(book_id)
    if book_in_db
      puts " ** book already in DB"
    end
    if ENV['overwrite']
      puts " ** saving (overwrite set)"
      save_book(book_id)
    elsif book_in_db.nil?
      puts " ** saving (not in DB yet)"
      save_book(book_id)
    else
      puts " ** skipping"
    end
  rescue StandardError => e
    puts " ** unable to save: #{e}"
  end
end
